Corner Grocer Inventory Analyzer: InventoryAnalyzer Class Reference
InventoryAnalyzer Class Reference
Public Member Functions
void Start ()
Private Member Functions
void printLogoPart1 ()
void printLogoPart2 ()
void printChadaTechLogo ()
void printWelcomeMessage ()
bool tryBuildDatabase ()
std::string getHeatmapColor (int t_count)
void printColorKey ()
void searchForItemByName ()
void displayCountOfAllItemsNumerical ()
void displayCountOfAllItemsHistogram ()
void mainMenu ()
Private Attributes
std::string m_inputFileName = "CS210_Project_Three_Input_File.txt"
std::string m_outputFileName = "frequency.dat"
int m_displayWidth = 80
std::string m_uiColor = "cyan"
Database m_database
std::vector< std::string > m_mainMenuOptions
std::vector< std::string > m_heatMapColors
Detailed Description
Inventory Analyzer class serves as the program controller.
Definition at line 548 of file main.cpp.
Member Function Documentation
displayCountOfAllItemsHistogram()
void InventoryAnalyzer::displayCountOfAllItemsHistogram () inline private
Displays the count of all items in a histogram.
Definition at line 762 of file main.cpp.
References Utils::centerStrings(), getHeatmapColor(), m_database, m_displayWidth, m_uiColor, printColorKey(), Utils::repeatString(), Utils::setConsoleTextColor(), and Utils::waitForEnter().
Referenced by mainMenu().
displayCountOfAllItemsNumerical()
void InventoryAnalyzer::displayCountOfAllItemsNumerical () inline private
Displays the count of all items numerically.
Definition at line 741 of file main.cpp.
References Utils::centerStrings(), getHeatmapColor(), m_database, m_displayWidth, m_uiColor, printColorKey(), Utils::setConsoleTextColor(), and Utils::waitForEnter().
Referenced by mainMenu().
getHeatmapColor()
std::string InventoryAnalyzer::getHeatmapColor (int t_count) inline private
Gets heatmap color.
Parameters
t_count the count of the item
Returns
the heatmap color
Definition at line 677 of file main.cpp.
References m_database, and m_heatMapColors.
Referenced by displayCountOfAllItemsHistogram(), displayCountOfAllItemsNumerical(), and searchForItemByName().
mainMenu()
void InventoryAnalyzer::mainMenu () inline private
Main menu loop.
Definition at line 784 of file main.cpp.
References displayCountOfAllItemsHistogram(), displayCountOfAllItemsNumerical(), Utils::getMenuChoice(), m_displayWidth, m_mainMenuOptions, m_uiColor, Utils::printMenu(), searchForItemByName(), and Utils::setConsoleTextColor().
Referenced by Start().
printChadaTechLogo()
void InventoryAnalyzer::printChadaTechLogo () inline private
Print ASCII Art Chada Tech Logo
Definition at line 601 of file main.cpp.
Referenced by Start().
printColorKey()
void InventoryAnalyzer::printColorKey () inline private
Prints the color key.
Definition at line 691 of file main.cpp.
References m_database, m_heatMapColors, m_uiColor, and Utils::setConsoleTextColor().
Referenced by displayCountOfAllItemsHistogram(), and displayCountOfAllItemsNumerical().
printLogoPart1()
void InventoryAnalyzer::printLogoPart1 () inline private
Prints ASCII Art Logo Part 1
Definition at line 572 of file main.cpp.
Referenced by printWelcomeMessage().
printLogoPart2()
void InventoryAnalyzer::printLogoPart2 () inline private
Prints ASCII Art Logo Part 2
Definition at line 587 of file main.cpp.
Referenced by printWelcomeMessage().
printWelcomeMessage()
void InventoryAnalyzer::printWelcomeMessage () inline private
Prints welcome message
Definition at line 637 of file main.cpp.
References Utils::centerString(), m_displayWidth, m_uiColor, printLogoPart1(), printLogoPart2(), and Utils::setConsoleTextColor().
Referenced by Start().
searchForItemByName()
void InventoryAnalyzer::searchForItemByName () inline private
Searches for an item by name.
Definition at line 709 of file main.cpp.
References Utils::centerStrings(), getHeatmapColor(), m_database, m_displayWidth, m_uiColor, Utils::setConsoleTextColor(), Utils::trim(), and Utils::waitForEnter().
Referenced by mainMenu().
Start()
void InventoryAnalyzer::Start () inline
Starts the inventory analyzer.
Definition at line 820 of file main.cpp.
References Utils::centerString(), Utils::clearScreen(), m_displayWidth, m_uiColor, mainMenu(), printChadaTechLogo(), printWelcomeMessage(), Utils::setConsoleTextColor(), tryBuildDatabase(), and Utils::waitForEnter().
Referenced by main().
tryBuildDatabase()
bool InventoryAnalyzer::tryBuildDatabase () inline private
Tries to build the database.
Returns
true if the database was built successfully, false otherwise
Definition at line 654 of file main.cpp.
References m_database, m_inputFileName, m_outputFileName, m_uiColor, Utils::setConsoleTextColor(), and Utils::waitForEnter().
Referenced by Start().
Member Data Documentation
m_database
Database InventoryAnalyzer::m_database private
Definition at line 554 of file main.cpp.
Referenced by displayCountOfAllItemsHistogram(), displayCountOfAllItemsNumerical(), getHeatmapColor(), printColorKey(), searchForItemByName(), and tryBuildDatabase().
m_displayWidth
int InventoryAnalyzer::m_displayWidth = 80 private
Definition at line 552 of file main.cpp.
Referenced by displayCountOfAllItemsHistogram(), displayCountOfAllItemsNumerical(), mainMenu(), printWelcomeMessage(), searchForItemByName(), and Start().
m_heatMapColors
std::vector<std::string> InventoryAnalyzer::m_heatMapColors private
Initial value:
= {
        "red",
        "yellow",
        "green",
        "blue",
    }
Definition at line 562 of file main.cpp.
Referenced by getHeatmapColor(), and printColorKey().
m_inputFileName
std::string InventoryAnalyzer::m_inputFileName = "CS210_Project_Three_Input_File.txt" private
Definition at line 550 of file main.cpp.
Referenced by tryBuildDatabase().
m_mainMenuOptions
std::vector<std::string> InventoryAnalyzer::m_mainMenuOptions private
Initial value:
= {
        "Search for Item by Name",
        "Display Count of All Items (Numerical)",
        "Display Count of All Items (Histogram)",
        "Exit"
    }
Definition at line 555 of file main.cpp.
Referenced by mainMenu().
m_outputFileName
std::string InventoryAnalyzer::m_outputFileName = "frequency.dat" private
Definition at line 551 of file main.cpp.
Referenced by tryBuildDatabase().
m_uiColor
std::string InventoryAnalyzer::m_uiColor = "cyan" private
Definition at line 553 of file main.cpp.
Referenced by displayCountOfAllItemsHistogram(), displayCountOfAllItemsNumerical(), mainMenu(), printColorKey(), printWelcomeMessage(), searchForItemByName(), Start(), and tryBuildDatabase().
The documentation for this class was generated from the following file:
main.cpp