Corner Grocer Inventory Analyzer: Utils Class Reference
Utils Class Reference
Static Public Member Functions
static void clearScreen ()
static void setConsoleTextColor (const std::string &t_color)
static void clearInputBuffer ()
static void waitForEnter ()
static std::string trim (const std::string &t_str)
static bool tryOpenInputFile (const std::string &t_fileName, std::ifstream &t_fileStream)
static bool tryOpenOutputFile (const std::string &t_fileName, std::ofstream &t_fileStream)
static size_t getDisplayLength (const std::string &t_str)
static std::string centerString (const std::string &t_str, unsigned int t_width, std::string t_paddingChar=" ", std::string t_startChar="", std::string t_endChar="")
static std::string centerStrings (const std::string t_str_left, const std::string t_str_right, unsigned int t_width, std::string t_separator=" ")
static int getIntegerInput (const std::string &t_prompt, const std::string &t_errorMessage, int t_minValue=1, int t_maxValue=2147483647)
static void printMenu (const std::string &t_title, const std::vector< std::string > &t_strings, unsigned int t_width)
static unsigned int getMenuChoice (unsigned int t_maxChoice)
static std::string repeatString (const std::string &t_str, int t_count)
static std::string createProgressBar (int t_width, double t_percent, std::string t_fillChar="█", std::string t_emptyChar="░")
static void printProgressBar (int t_lineCount, int t_currentLine, int t_width=40)
Detailed Description
main.cpp
Author: Benjamin Orona, Chada Tech Client: Corner Grocer Date: 6/20/2025 Class: CS-210 Programming Languages Assignment: 7-3 Project Three
Purpose: Inventory analyzer This program allows users to analyze the inventory of a store. The program will read a file containing purchases for the day. The program will then display the number of each item sold using different display options. The program will also write the results to a file.
Input file: CS210_Project_Three_Input_File.txt Input example: Apple Banana Orange Apple
Output file: frequency.dat Output example: Apple 2 Banana 1 Orange 1
Usage: ./main Utility class for the inventory analyzer
Definition at line 53 of file main.cpp.
Member Function Documentation
centerString()
std::string Utils::centerString (const std::string & t_str, unsigned int t_width, std::string t_paddingChar = " ", std::string t_startChar = "", std::string t_endChar = "") inline static
Centers a string within a given width.
Parameters
t_str the string to center
t_width the width of the output
t_paddingChar the character to use for padding
t_startChar the character to use for the start of the string
t_endChar the character to use for the end of the string
Returns
the centered string, the original string if it is longer than the width
Definition at line 211 of file main.cpp.
References getDisplayLength(), and repeatString().
Referenced by printMenu(), InventoryAnalyzer::printWelcomeMessage(), and InventoryAnalyzer::Start().
centerStrings()
std::string Utils::centerStrings (const std::string t_str_left, const std::string t_str_right, unsigned int t_width, std::string t_separator = " ") inline static
Centers two strings within a given width.
Parameters
t_str_left the left string to center
t_str_right the right string to center
t_width the width of the output
t_separator the separator to use between the two strings (optional, default is " ")
Returns
the centered strings
Definition at line 238 of file main.cpp.
References getDisplayLength().
Referenced by InventoryAnalyzer::displayCountOfAllItemsHistogram(), InventoryAnalyzer::displayCountOfAllItemsNumerical(), and InventoryAnalyzer::searchForItemByName().
clearInputBuffer()
void Utils::clearInputBuffer () inline static
Clears the input buffer.
Definition at line 115 of file main.cpp.
clearScreen()
void Utils::clearScreen () inline static
Clears the console screen in a cross-platform way.
Definition at line 58 of file main.cpp.
Referenced by InventoryAnalyzer::Start().
createProgressBar()
std::string Utils::createProgressBar (int t_width, double t_percent, std::string t_fillChar = "█", std::string t_emptyChar = "░") inline static
Creates a progress bar with a given width and percentage.
Parameters
t_width the width of the progress bar
t_percentage the percentage to display
Returns
the progress bar
Definition at line 354 of file main.cpp.
References repeatString().
Referenced by printProgressBar().
getDisplayLength()
size_t Utils::getDisplayLength (const std::string & t_str) inline static
Gets the display length of a string (number of visible characters). This is different from string.length() which returns bytes.
Parameters
t_str the string to measure
Returns
the number of visible characters
Definition at line 191 of file main.cpp.
Referenced by centerString(), centerStrings(), and printMenu().
getIntegerInput()
int Utils::getIntegerInput (const std::string & t_prompt, const std::string & t_errorMessage, int t_minValue = 1, int t_maxValue = 2147483647) inline static
Gets and validates integer input from the user.
Parameters
t_prompt the prompt to display to the user
t_errorMessage the error message to display if the input is invalid
t_minValue the minimum value the input can be (optional, default is 1)
t_maxValue the maximum value the input can be (optional, default is max int)
Returns
the integer input
Definition at line 256 of file main.cpp.
Referenced by getMenuChoice().
getMenuChoice()
unsigned int Utils::getMenuChoice (unsigned int t_maxChoice) inline static
Gets menu choice 1 through maxChoice, inclusive.
Parameters
t_maxChoice the maximum choice index, must be greater than 0
Exceptions
std::invalid_argument if t_maxChoice is 0
Returns
the first legal choice input, could be 1 through t_maxChoice, inclusive
Definition at line 322 of file main.cpp.
References getIntegerInput().
Referenced by InventoryAnalyzer::mainMenu().
printMenu()
void Utils::printMenu (const std::string & t_title, const std::vector< std::string > & t_strings, unsigned int t_width) inline static
Prints a menu with numbered options.
Parameters
t_title the title of the menu
t_strings the array of choices
t_width the width of each line
Definition at line 291 of file main.cpp.
References centerString(), and getDisplayLength().
Referenced by InventoryAnalyzer::mainMenu().
printProgressBar()
void Utils::printProgressBar (int t_lineCount, int t_currentLine, int t_width = 40) inline static
Prints progress bar based on line count with delay so user can see progress.
Parameters
t_lineCount the line count to print the progress bar for
t_currentLine the current line to print the progress bar for
t_width the width of the progress bar
Definition at line 372 of file main.cpp.
References createProgressBar().
Referenced by Database::buildDatabaseFromFile(), and Database::writeDatabaseBackup().
repeatString()
std::string Utils::repeatString (const std::string & t_str, int t_count) inline static
Creates a string of repeated characters using a string input for unicode support.
Parameters
t_str the string to repeat
t_count number of times to repeat
Returns
string of repeated characters
Definition at line 339 of file main.cpp.
Referenced by centerString(), createProgressBar(), and InventoryAnalyzer::displayCountOfAllItemsHistogram().
setConsoleTextColor()
void Utils::setConsoleTextColor (const std::string & t_color) inline static
Sets the console text color
Parameters
t_color the color to set
Exceptions
std::invalid_argument if the color is invalid
Definition at line 72 of file main.cpp.
Referenced by Database::buildDatabaseFromFile(), InventoryAnalyzer::displayCountOfAllItemsHistogram(), InventoryAnalyzer::displayCountOfAllItemsNumerical(), InventoryAnalyzer::mainMenu(), InventoryAnalyzer::printColorKey(), InventoryAnalyzer::printWelcomeMessage(), InventoryAnalyzer::searchForItemByName(), InventoryAnalyzer::Start(), InventoryAnalyzer::tryBuildDatabase(), and Database::writeDatabaseBackup().
trim()
std::string Utils::trim (const std::string & t_str) inline static
Removes leading and trailing whitespace from a string. Whitespace characters are: space, tab, carriage return, and newline.
Parameters
t_str the string to trim
Returns
the trimmed string
Definition at line 136 of file main.cpp.
Referenced by Database::buildDatabaseFromFile(), InventoryAnalyzer::searchForItemByName(), and Database::tryGetItemCount().
tryOpenInputFile()
bool Utils::tryOpenInputFile (const std::string & t_fileName, std::ifstream & t_fileStream) inline static
Opens an input file and checks if it exists.
Parameters
t_fileName the name of the file to open
t_fileStream the file stream to open
Returns
true if the file was opened successfully, false otherwise
Definition at line 155 of file main.cpp.
Referenced by Database::buildDatabaseFromFile().
tryOpenOutputFile()
bool Utils::tryOpenOutputFile (const std::string & t_fileName, std::ofstream & t_fileStream) inline static
Opens an output file and checks if it exists and if the program has permission to create it.
Parameters
t_fileName the name of the file to open
t_fileStream the file stream to open
Returns
true if the file was opened successfully, false otherwise
Definition at line 173 of file main.cpp.
Referenced by Database::writeDatabaseBackup().
waitForEnter()
void Utils::waitForEnter () inline static
Waits for the user to press Enter.
Definition at line 123 of file main.cpp.
Referenced by InventoryAnalyzer::displayCountOfAllItemsHistogram(), InventoryAnalyzer::displayCountOfAllItemsNumerical(), InventoryAnalyzer::searchForItemByName(), InventoryAnalyzer::Start(), and InventoryAnalyzer::tryBuildDatabase().
The documentation for this class was generated from the following file:
main.cpp