Corner Grocer Inventory Analyzer: Database Class Reference
Database Class Reference
Classes
class DatabaseError
Public Member Functions
void buildDatabaseFromFile (const std::string &t_inputFileName)
void writeDatabaseBackup (const std::string &t_outputFileName)
bool tryGetItemCount (const std::string &t_item, int &t_count)
std::map< std::string, int > getItemCounts ()
int getMaxItemCount ()
Private Member Functions
int getLineCount (std::ifstream &t_inputFileStream)
Private Attributes
std::map< std::string, int > m_itemCounts
int m_maxItemCount = 0
Detailed Description
Database class that stores item counts and provides methods to search and display the data.
Definition at line 388 of file main.cpp.
Member Function Documentation
buildDatabaseFromFile()
void Database::buildDatabaseFromFile (const std::string & t_inputFileName) inline
Builds the database from the input file.
Exceptions
DatabaseError if the database cannot be built
Definition at line 428 of file main.cpp.
References getLineCount(), m_itemCounts, m_maxItemCount, Utils::printProgressBar(), Utils::setConsoleTextColor(), Utils::trim(), and Utils::tryOpenInputFile().
getItemCounts()
std::map< std::string, int > Database::getItemCounts () inline
Gets the item counts.
Returns
the item counts
Definition at line 531 of file main.cpp.
References m_itemCounts.
getLineCount()
int Database::getLineCount (std::ifstream & t_inputFileStream) inline private
Gets the line count of a file.
Parameters
t_inputFileStream the file stream to get the line count of
Returns
the line count of the file
Definition at line 405 of file main.cpp.
Referenced by buildDatabaseFromFile().
getMaxItemCount()
int Database::getMaxItemCount () inline
Gets the max item count.
Returns
the max item count
Definition at line 540 of file main.cpp.
References m_maxItemCount.
tryGetItemCount()
bool Database::tryGetItemCount (const std::string & t_item, int & t_count) inline
Tries to get the count of an item.
Parameters
t_item the item to get the count of
t_count the count of the item
Returns
true if the count was found, false otherwise
Definition at line 502 of file main.cpp.
References m_itemCounts, and Utils::trim().
writeDatabaseBackup()
void Database::writeDatabaseBackup (const std::string & t_outputFileName) inline
Write database backup to file.
Exceptions
DatabaseError if the database cannot be written
Definition at line 472 of file main.cpp.
References m_itemCounts, Utils::printProgressBar(), Utils::setConsoleTextColor(), and Utils::tryOpenOutputFile().
Member Data Documentation
m_itemCounts
std::map<std::string, int> Database::m_itemCounts private
Definition at line 396 of file main.cpp.
Referenced by buildDatabaseFromFile(), getItemCounts(), tryGetItemCount(), and writeDatabaseBackup().
m_maxItemCount
int Database::m_maxItemCount = 0 private
Definition at line 397 of file main.cpp.
Referenced by buildDatabaseFromFile(), and getMaxItemCount().
The documentation for this class was generated from the following file:
main.cpp